services:
    wjb_rewire.cache_warmer:
        class: wjb\RewireBundle\Cache\RewireParamsAnnotationsWarmer
        arguments: ['@router', '@annotations.reader']
        tags:
            - { name: kernel.cache_warmer, priority: -100 }

    wjb_rewire.router_decorator:
        class: wjb\RewireBundle\Decorator\RoutingDecorator
        decorates: router
        arguments: ['@wjb_rewire.router_decorator.inner', '%kernel.cache_dir%']
