services:

    wjb\RewireBundle\Cache\RewireParamsAnnotationsWarmer:
        arguments: ['@router', '@annotations.reader']
        tags:
            - { name: kernel.cache_warmer, priority: -100 }

    wjb_rewire.routing_extension_decorator:
        class: wjb\RewireBundle\Decorator\RoutingExtensionDecorator
        decorates: twig.extension.routing
        arguments: ['@router', '%kernel.cache_dir%']
